export const initTodos = [
    { id: 1, description: 'Hacer algo 1', tags: ['javascript'], completed: false, title: 'Esto es una descripción de prueba más larga que la que tenía antes.', priority: 'high'},
    { id: 2, description: 'Hacer algo 2', tags: ['javascript'], completed: false, title: 'My false todo 2', priority: 'medium'},
    { id: 3, description: 'Hacer algo 3', tags: ['javascript'], completed: false, title: 'My false todo 3', priority: 'low'},
    { id: 4, description: 'Hacer algo 4', tags: ['javascript'], completed: false, title: 'My false todo 4', priority: 'low'},
    { id: 5, description: 'Hacer algo 5', tags: ['javascript'], completed: false, title: 'My false todo 5', priority: 'medium'},
    { id: 6, description: 'Hacer algo 6', tags: ['javascript'], completed: false, title: 'My false todo 6', priority: 'medium'},
    { id: 7, description: 'Hacer algo 7', tags: ['javascript'], completed: false, title: 'My false todo 7', priority: 'low'},
    { id: 8, description: 'Hacer algo 8', tags: ['javascript'], completed: false, title: 'My false todo 8', priority: 'low'},
    { id: 9, description: 'Hacer algo 9', tags: ['javascript'], completed: false, title: 'My false todo 9', priority: 'medium'},
    { id: 10, description: 'Hacer algo 10', tags: ['javascript'], completed: false, title: 'My false todo 10', priority: 'medium'},
    { id: 11, description: 'Hacer algo 11', tags: ['javascript'], completed: false, title: 'My false todo 11', priority: 'low'},
    { id: 12, description: 'Hacer algo 12', tags: ['javascript'], completed: false, title: 'My false todo 12', priority: 'low'},
    { id: 13, description: 'Hacer algo 13', tags: ['javascript'], completed: false, title: 'My false todo 13', priority: 'medium'},
    { id: 14, description: 'Hacer algo 14', tags: ['javascript'], completed: false, title: 'My false todo 14', priority: 'medium'},
    { id: 15, description: 'Hacer algo 15', tags: ['javascript'], completed: false, title: 'My false todo 15', priority: 'low'},
    { id: 16, description: 'Hacer algo 16', tags: ['javascript'], completed: false, title: 'My false todo 16', priority: 'low'},
    { id: 17, description: 'Hacer algo 17', tags: ['javascript'], completed: false, title: 'My false todo 17', priority: 'medium'},
]